export const CHANGE_SEARCHFIELD = "CHANGE_SEARCHFIELD";

export const REQUEST_KITTYS_PENDING = "REQUEST_KITTYS_PENDING";
export const REQUEST_KITTYS_SUCCESS = "REQUEST_KITTYS_SUCCESS";
export const REQUEST_KITTYS_FAILED = "REQUEST_KITTYS_FAILED";
